name: Linux

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          graalvm: '22.1.0.1-Final'

      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: Make staging directory
        run: mkdir staging

      # - name: Gluon License
      #   uses: gluonhq/gluon-build-license@v1
      #   with:
      #     gluon-license: ${{ secrets.GLUON_LICENSE }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build nativeBuild

      - name: Copy native client to staging
        run: cp -r build/gluonfx/x86_64-linux/TekkenBackupService* staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

      # download the JAR from job 'build'
      - uses: actions/download-artifact@v2
        with:
          path: staging

      # upload it to the release corresponding to the current Git tag (2)
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: TekkenBackupService*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
