name: MacOS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7.0'

      - uses: actions/checkout@v2
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 20.3.0.java11

      - name: Make staging directory
        run: mkdir staging

      - name: Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}

      - name: Gluon Build
        run: gradle nativeBuild
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}

      - name: Copy native client to staging
        run: cp -r build/client/x86_64-darwin/TekkenBackupService* staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

      # download the JAR from job 'build'
      - uses: actions/download-artifact@v2
        with:
          path: staging

      # upload it to the release corresponding to the current Git tag (2)
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: TekkenBackupService*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
