name: Java CI with Gradle

on:
  push:
    tags:
      - v*
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          graalvm: '22.1.0.1-Final'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test
        run: ./gradlew test
      - name: Assemble
        run: ./gradlew assemble
      - name: Check
        run: ./gradlew check
      - name: Jar
        run: ./gradlew jar
      - name: Native Image
        run: ./gradlew nativeImage
      - name: Publish to GitHub Packages
        run: ./gradlew publish
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tekken-backup-service-${{ matrix.os }}
          path: build/libs/*.jar
